name: Notification Grade

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    name: Send Data
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      

    - name: Install python package # 파이썬 관련 패키지를 설치하고
      run: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python3 get-pip.py        
        pip3 install selenium
        pip3 install requests
        
    - name: Install ubuntu package # 우분투 관련 패키지도 설치한 후
      run: |
        sudo apt-get install google-chrome-stable    
        wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
        unzip ./chromedriver_linux64.zip   
        
    - name: Run main.py
      run: python main.py ${{ secrets.WEBHOOK }} ${{ secrets.STD_ID }} ${{ secrets.PASSWD }}
